using System.Collections;
using System.Collections.Generic;
using UnityEngine;

public class PlayerLimits : MonoBehaviour
{


    private List<int> amount;

    private int digAmount = 1;
    private int crossbowAmount = 1;
    private int canonAmount = 1;
    private int summonAmount = 1;
    private int healingSpell = 1;

    // Start is called before the first frame update
    void Start()
    {
        
    }

    // Update is called once per frame
    void Update()
    {
        
    }
    public void Increase(int increaser, int increaseAmount)
    {
        amount[increaser] += increaseAmount;

    }
    //public void IncreaseDig(int increaseAmount)
    //{
    //    digAmount += increaseAmount;

    //}
    //public void IncreaseCrossbow()
    //{



    //}
    //public void IncreasCannon(int increaseAmount)
    //{

    //    canonAmount += increaseAmount;

    //}
    //public void SummonIncrease()
    //{



    }


    //public bool doIhaveEnough(string)
    //{



    //    return 
    //}









